### ISSUE TITLE
Horrible performance for operations combining floats and intervals

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#104]
```jl
julia> x = 0.1..0.2
[0.0999999, 0.200001]

julia> @btime 3.1 + $x
  332.254 ns (3 allocations: 128 bytes)
[3.19999, 3.30001]
```
This is due to the fact that the promotion machinery calls `convert(Interval{Float64}, 3.1)`, which is now very slow again. 

Maybe we should just write explicit methods for operations of the form `op(x::Number, y::Interval)`.

**Comment by dpsanders** [comment]
```jl
+(x::Real, y::Interval) = Interval(x) + y
```
etc.

**Comment by lbenet** [comment]
While i think it is a good idea to avoid promotion, I don't see how will we avoid rounding, which is not considered above. An example would simply be `0.1 + Interval(0.0)`.

**Comment by dpsanders** [comment]
I think we can just do `Interval(prevfloat(x), nextfloat(x))`.

**Comment by dpsanders** [comment]
The problem seems to be in `find_quadrants` in
`temp = x / half_pi(x)`

**Comment by dpsanders** [comment]
But `sin` is still very slow.

**Comment by dpsanders** [comment]
There is a huge discrepancy due to finding the quadrants:

```
julia> x = 3..4

julia> @btime IntervalArithmetic.@round(sin($x.lo), sin($x.hi))
  44.328 ns (0 allocations: 0 bytes)

julia> @btime sin($x)
  700.951 ns (14 allocations: 448 bytes)
[-0.756803, 0.141121]
```

**Comment by dpsanders** [comment]
```
julia> @btime Interval($y) / IntervalArithmetic.half_pi($y)
  36.213 ns (0 allocations: 0 bytes)
```
So the total time should be something like 80ns (which is still slow compared to other libraries :/ )

**Comment by tkoolen** [comment]
Just my two cents (partly from https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/108): I'm probably missing something, but why not:

1. define
    ```julia
     convert(::Type{Interval{T}}, x::T) where {T<:Real} = Interval{T}(x)
     convert(::Type{Interval{T}}, x::T) where {T<:AbstractFloat} = Interval{T}(x)
     ```
    so that these conversions are fast and the resulting interval is as tight as possible (namely a trivial interval).
1. move the rounding/widening code from the current `convert` methods to a separate function, say `floatingpointclosure(::Type{T}, x::S) where {T<:AbstractFloat, S<:Real}`, returning an `Interval{T}`. This is the slow code.
1. call `floatingpointclosure` from `@interval` instead of `convert`.
1. call `floatingpointclosure` from `convert(::Type{Interval{T}}, x::S)` methods where the destination `Interval` element type is *not* the same as the type of `x` (i.e. less specific `convert` methods than the ones I listed under 1.).

**Comment by dpsanders** [comment]
We did have a discusdion along these lines at some point. I think this is a good idea. What's your take, @lbenet?

**Comment by lbenet** [comment]
The whole idea seems quite appealing. My only concern is related to ensure that the returned interval is rigorous and tight as possible. If I understand the plan, this is done at point 2. Am I right? I'll take a look in #114.
