### ISSUE TITLE
Add `rand`/`randn`?

### ISSUE THREAD

**Issue by tkoolen** [JuliaIntervals/IntervalArithmetic.jl#109]
Would it make sense to have

```julia
Compat.Random.rand(rng::AbstractRNG, ::Type{Interval{T}}) where {T} = Interval(rand(rng, T))
Compat.Random.randn(rng::AbstractRNG, ::Type{Interval{T}}) where {T} = Interval(randn(rng, T))
```

?

**Comment by dpsanders** [comment]
There is also an argument that is should instead return an interval with two different random endpoints.

It certainly makes sense to have a function to generate some kind of random interval. Since it's not so clear (to me) what a "canonical" random interval would look like, perhaps it does not make so much sense to extend `rand`?

**Comment by tkoolen** [comment]
Yeah, that makes sense; I suppose it's not clear which one is "right". Probably better to require the user to be explicit about which one is desired (and thus not define methods for `rand`/`randn`).
