### ISSUE TITLE
Interval(1..2, 3..4) crashes Julia

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#182]
[Mistake for IntervalBox.]

**Comment by dpsanders** [comment]
On 0.6; IA on Julia 0.7 is currently broken.

**Comment by Kolaru** [comment]
It seems to be a display issue:

```julia
julia> Interval(1..2, 3..4)
Error showing value of type IntervalArithmetic.Interval{IntervalArithmetic.Interval{Float64}}:
ERROR: StackOverflowError:

julia> setformat(:full)
6

julia> Interval(1..2, 3..4)
Interval(Interval(1.0, 2.0), Interval(3.0, 4.0))
```

It doesn't crash the REPL for me (Julia 0.6.4 on Windows) thought.

The `StackOverflowError` probably means there is an infinite recursive call somewhere, I will try to hunt it down.

**Comment by Kolaru** [comment]
The crash comes from [here](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/cab2433d6719899c38c0c3514fc935208614bdd0/src/display.jl#L125):

```julia
round_string(x::Real, digits::Int, r::RoundingMode) = round_string(big(x), digits, r)
```

If `x` is an `Interval`, it is a real as well, but `big(x)` is still an interval. Therefore `big(x)` never becomes a `BigFloat` which is needed to switch to another method, hence the infinite recursion.

However, we should probably not silently accept something like `Interval(1..2, 3..4)`... we could be lenient and return an `IntervalBox`, which would be very misleading, but works fine, or we could just return an error.

Interestingly enough, this boils down to the fact that since `Interval`s (and others) are `Real` we can not assume that `Real` only means the `Integer`, `Float` and `BigFloat` families, which is related to #181.

**Comment by dpsanders** [comment]
Thanks for finding the problem!

I think this should just give an error.
