### ISSUE TITLE
Use cases for package in other packages and papers

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#184]
It would be very helpful if people were willing to list some of the use cases of this package, both within other Julia packages and for calculations published in research papers etc.

EDIT: Please just add a comment with links.

**Comment by mforets** [comment]
Use case: applications of formal verification. We use it in [JuliaReach](http://www.juliareach.org/), such as in the packages [LazySets.jl](https://github.com/JuliaReach/LazySets.jl) and [Reachability.jl](https://github.com/JuliaReach/Reachability.jl) as a basic set representation for reach pipe calculations of dynamical systems.

**Comment by Kolaru** [comment]
Use case: Count the number of non-trivial solutions of a system of equations to determine the different phases of the system and independantly verify analytic result determining the critical region of the transition. Interval arithmetic was also used to prove that in some cases the phase transition is discontinous.

I did this for my [master thesis](https://github.com/Kolaru/MasterThesis) in the context of network studies. For the final results, see figures 2.6 and 2.7 of the [report](https://github.com/Kolaru/MasterThesis/blob/master/Report/reportmain.pdf).

**Comment by kalmarek** [comment]
@dpsanders we had a chat at some point about citing `IntervalArithmetic` (or `ValidatedNumerics`) has a paper about it (or even a technical report) been published since?

My application: providing certified lower bounds on the spectral gap of the group Laplace operators.
This includes:
 * https://arxiv.org/abs/1703.09680, or https://www.degruyter.com/view/j/gcc.2018.10.issue-1/gcc-2018-0004/gcc-2018-0004.xml
 * https://arxiv.org/abs/1712.07167 has been recently accepted, I'd be very happy to add `IntervalArithmetic` to References!
 * https://arxiv.org/abs/1812.03456 is still pending review (and will be for forseable future ;-)

**Comment by lbenet** [comment]
Sorry for the long delay, and thanks for asking. I guess (for the time being) the best is to cite the package as:

```
David P. Sanders and Luis Benet
JuliaIntervals/IntervalArithmetic.jl:
Rigorous floating-point calculations using interval arithmetic in Julia (Version v0.x.x).
https://github.com/JuliaIntervals/IntervalArithmetic.jl
```

It is a good idea to specify the version you used.

cc @dpsanders

**Comment by kalmarek** [comment]
@lbenet the nice thing about projects is that the version will be fixed by `Manifest.toml` which will be distributed alongside the paper

**Comment by lbenet** [comment]
@kalmarek Sorry for the late reply; somehow your reply got lost. I agree with you, but this is something maybe unknown by a reader of the bibliography.

**Comment by gwater** [comment]
[our peer-reviewed article](https://iopscience.iop.org/article/10.1088/1367-2630/aae998/meta) about delay differential equations references IntervalRootFinding.jl

**Comment by lucaferranti** [comment]
there's also #471, which is pinged
