### ISSUE TITLE
Remove `@interval` from tests

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#298]
We no longer should `@interval` in tests. This is basically no longer used in the package.
It should be replaced by `interval(a, b)` or `a..b`.

**Comment by dpsanders** [comment]
cc @yashrajgupta

**Comment by Kolaru** [comment]
Should we remove `@interval` (and associated `@floatinterval` and `@biginterval`) altogether from the package ? (it is currently only used internally to process the string prefix, e.g. `I"[0.1, 7.2]"`).

I'm also in favor of removing `interval(a, b)`, it is the same as `Interval(a, b)` but check that the bounds are well ordered. This could be achieved more explicitly by allowing a `check` flag in `Interval` constructor i.e. `Interval(a, b; check=False)` where setting `check` to `True` check that the bounds are well ordered.

**Comment by dpsanders** [comment]
`@interval` is necessary in situations such as
`@interval sin(0.1) + cos(0.2)` to ensure that the literals are wrapped correctly, if we want to assume that the user means by `0.1` the true real number `1//10`. Maybe we should just completely remove all such "interpretations" though.

Then we could have `a..b` construct the interval between the floating-point numbers `a` and `b` with no rounding at all. 

I am not really in favour of having the user type `Interval(a, b; check=true)` just to construct an interval, and we need the more efficient version internally to avoid unnecessary checks.

**Comment by Kolaru** [comment]
> `@interval` is necessary in situations such as
> `@interval sin(0.1) + cos(0.2)` to ensure that the literals are wrapped correctly, if we want to assume that the user means by `0.1` the true real number `1//10`. Maybe we should just completely remove all such "interpretations" though.

Since `@interval sin(0.1) + cos(0.2)` is really equivalent to `sin(I"0.1") + cos(I"0.2")` the advantage of the extra construct is not huge. In general, users using literaly should always replace them by the string version anyway to get guaranteed result, documenting that may be more helpful than maintaining this construction macro.

For example here
```julia
a = sin(0.1) + cos(0.2)
b = 1.1 * a
```
The correct interval version is
```julia
a = sin(I"0.1") + cos(I"0.2")
b = I"1.1" * a
```
And the `@interval` macro would not be enough.


> I am not really in favour of having the user type `Interval(a, b; check=true)` just to construct an interval, and we need the more efficient version internally to avoid unnecessary checks.

Efficiency is no concern here has this method would only be chosen if a keyword argument is given (non keyword methods seem to be considered more specific otherwise), giving direct access to the unchecked version.

Documenting `a..b` as the preferred user facing constructor may be sufficient too. My objection there was really that having both `interval(a, b)` and `Interval(a, b)` is confusing.

**Comment by lbenet** [comment]
I am in favor of having a way in which an interval does contain the true number, which usually is what the user wants. (Though, ocasionally, the user *believes* that 0.1 is precisely 1//10.) This is something I like from the `a .. b` constructor, which I think we should keep as it is now, and which works fine for `0.1 .. 0.1`. 

Regarding `@interval` I actually like it, precisely because it works on expressions. We should maybe get rid of `@floatinterval`, but please keep `@biginterval`; I think it is a positive aspect of `IntervalArithmetics.jl` the possibility of using extended precision out of the box, which may only be compared with MPFI.

We had a long discussion about checking the order of the bounds when constructing an interval. this lead to the distinction of `interval` and `Interval`; I think the relevant issue was #36, but maybe it was elsewhere as well. Performance was a decisive point in the discussion. I would not mind having only `Interval`, and maybe a constructor with a `check` flag, which actually looks pretty julian. If we opt for that, we should have a way of setting the default by the user. 

Rather than performance (but also without forgetting it), I am always in favor of having rigorous bounds.

**Comment by lbenet** [comment]
> Since @interval sin(0.1) + cos(0.2) is really equivalent to sin(I"0.1") + cos(I"0.2") the advantage of the extra construct is not huge. In general, users using literaly should always replace them by the string version anyway to get guaranteed result, documenting that may be more helpful than maintaining this construction macro.

I fully agree; yet, I don't think we have something similar for `Interval{BigFloat}`, though maybe we should have something like `B"0.1"`...

**Comment by dpsanders** [comment]
The goal of `@interval` was exactly to have a way of expressing a valid interval construction, *without* having to wrap each literal in anything. In your example, we could do e.g.
```
julia> a = @interval sin(0.1) + cos(0.2)
Interval(1.0798999944880696, 1.07989999448807)

julia> b = @interval 1.1 * a
Interval(1.1878899939368763, 1.1878899939368772)
```
although it may be that we should look again at the implementation of `@interval` and make sure that it has correct hygiene behaviour.  

In summary, I do not see any particular advantage in removing `@interval` from the package, just make clear that it is not the usual way of constructing single intervals like `0.1..0.2`.

**Comment by Kolaru** [comment]
I came to conclusion it is indeed an interesting feature, but to get it to its full potential, it may need an extension like allowing escaping literals in block of code
```julia
@interval begin
    a = sin(0.1) + cos(0.2)
    b = 1.1 * a
end
```

Also it not really about creating interval, so renaming it to `@escape_literals` may make it clearer (but that's a different issue).

I have to look more in detail about `@biginterval` and realted stuff, because implementing a flavor system has the side effect of forcing to pick one of the flavors as the default one, which may get in the way here.
