### ISSUE TITLE
Float interval + BigFloat interval should be Float interval?

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#326]
`x::Interval{Float64}` + `y::Interval{BigFloat}` should give `Interval{Float64}`?

**Comment by lbenet** [comment]
Thanks for bringing this up, it is really a good point. 

I think that if a user takes the time to create an `Interval{BigFloat}` is because the user is precisely after that type of answer.

**Comment by perrutquist** [comment]
If the result is larger than `prevfloat(typemax(Float64))`, then the interval would have to be expanded all the way to infinity in order to be represented using `Float64`.

**Comment by dpsanders** [comment]
This is (partially) analogous to a similar discussion in TaylorSeries.jl about the degree of the sum of two polynomials of different degrees.

If one of the intervals is a Float64 then you can only have information at the precision level of a Float64.

The point about `prevfloat` is already handled:
```jl
julia> interval(0, prevfloat(typemax(Float64))) + Interval{Float64}(interval(big(1), big(2)))
Interval(1.0, Inf)
```

**Comment by perrutquist** [comment]
I would argue that the precision of a Float64 is infinite in this context, since results are always rounded in the right direction. (The numbers that are stored are not approximations of the bounds. They are the bounds, albeit not always the tightest possible bounds.)

For example, if I write `big"1e20" + (0..1)`. then I might consider that last interval to be exact, even though it happens to be stored as `Float64`. Therefore I would expect the result to be `big"100000000000000000000" .. big"100000000000000000001"`. Converting to `Interval{Float64}` would result in `100000000000000000000 .. 100000000000000016384`.

**Comment by dpsanders** [comment]
I see your point, but while you might know that you meant an exact interval, Julia has no way of knowing that. The fact that you chose to use an `Interval{Float64}` there, rather than a `BigFloat` (or, say, an interval of rational numbers) means that Julia should assume that you only have that amount of precision.

**Comment by Kolaru** [comment]
Discussed in triage, there are two reason have `Interval{Float64} + BigFloat -> BigFloat`
1. It follows `Base` convention.
2. The operation is still guaranteed, only the subsequent operation will be performed with higher precision.
