### ISSUE TITLE
Correlated Intervals

### ISSUE THREAD

**Issue by jonniedie** [JuliaIntervals/IntervalArithmetic.jl#334]
I'm not sure how it fits in with the mathematics of interval arithmetic, but it would be nice to have correlated intervals. For example, using```X=-∞..∞```, it would be intuitive for ```X^2``` and ```X*X``` to give the same interval ```[0, ∞]``` rather than having the latter be ```[-∞, ∞]```. I'm not sure how the machinery would work to achieve this, but I know Measurements.jl does something similar.

On the other hand, maybe the extra calculations required to implement the correlation will be more costly than just using uncorrelated intervals and taking a few extra bisections (or whatever method of interval shrinking is actually used).

**Comment by dpsanders** [comment]
Check out AffineArithmetic.jl which is one solution for this.

I did talk to the author of Measurements.jl but I think I concluded that the same idea can't exactly work for intervals.

**Comment by lbenet** [comment]
This is related with the so-called "dependency problem" in interval arithmetic. Thinking about intervals as sets, X*Y is the set {x*y | x ∈ X and y ∈ Y}, where `x` and `y` are considered independently from each other. Therefore, for X*X the answer corresponds to the set {x1*x2 | x1 ∈ X and x2 ∈ X} and not to {x*x | x ∈ X}.

I guess that what you mean by correlated intervals is to identify that both intervals are the same, and then return as the result {x*x | x ∈ X}; such an identification would have some cost.

**Comment by Kolaru** [comment]
To identify that two intervals are the same (in the strict sense that they represent the same variable, which is needed to have `X*X == X^2`), you need to tag each interval with an unique identifier and implement some kind of special rules in cases you encounter the same interval multiple time (`Measurements.jl` seems to be doing something like that, `ForwardDiff.jl` too in order to track dependent variables).

I pondered about it some times ago and arrived at the (possibly hasty) conclusion that at the end of the day, to be really useful, that would be equivalent to a full engine for symbolic computation (it would for example need factorization like `4*X - X == 3*X`). And even so, I'm not sure that an "optimal expression for IA" exists (e.g. which is better `X^2 - X` or `X*(X - 1)` ?).

Other strategies may be more easily applicable though, like trying to identify monotonic functions.

**Comment by Kolaru** [comment]
I thought about it a bit more and it looks like the optimal form regarding dependent intervals for the example I gave is actually `X^2 - X == (X + 0.5)^2 - 0.25` (that is completing the square to keep mostly operation between the interval and literals). I wonder if a compilation of that kind of tricks has been written somewhere (or if there is literature on the subject out there).

**Comment by dpsanders** [comment]
That parricular trick is known; I'm not sure about a compendium.

But as you said it needs some amount of symbolics. People have certainly tried to do things like that but I'm not sure how successful it's been or where to point to.

**Comment by OlivierHnt** [comment]
What is the status of this issue? As far as I can tell, IntervalArithmetic.jl does not aim to support such a feature.

**Comment by Kolaru** [comment]
As discuss in today's call, it is outside the scope of this package.

Currently, the go-to for that kind of stuff are either AffineArithmetic.jl or TaylorModels.jl

But if anyone has great ideas beyond those, we would be happy to hear about them.
