### ISSUE TITLE
Change base type of Interval{<: AbstractFloat} to AbstractFloat?

### ISSUE THREAD

**Issue by mfherbst** [JuliaIntervals/IntervalArithmetic.jl#335]
The question on the base type of Interval has already been mentioned here, e.g. in #310 or #41. I am wondering what is the current status and philosophy on this? Are there any updates? Is it even a realistic option to achieve this at some point in the future at least for a few interval types where this might make sense?

**Comment by Kolaru** [comment]
The main plan for `IntervalArithmetic.jl` (as far as I can tell) is to try to finish the ambitious PR #271, that is a full flavor system that will allow intervals of various base types, including `AbstractFloat`.

The status of this PR is currently "Kolaru got overdramatic about a minor setback and didn't touch it since, but will hopefully go back working on it soon".

Parallel to this, @gwater implemented intervals that are floats here https://github.com/gwater/NumberIntervals.jl, and it may suits your needs.

**Comment by dpsanders** [comment]
What's the minor setback? Should we discuss it?

**Comment by mfherbst** [comment]
@Kolaru Thanks for the clarification and the update. I'll take a look at NumberIntervals for the time being. Still ... a big round of encouragement from my end to pick up PR #271 at some point :smile:.

**Comment by Kolaru** [comment]
Discussed in the biweekly call: With the current philosophy on master, we believe this is resolved. We keep the `Real` supertype, while disallowing the problematic interactions.
