### ISSUE TITLE
Use IntervalSets.jl for set operations

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#366]
cf. discussion in https://github.com/JuliaMath/IntervalSets.jl/pull/55

This is related to redefining `..` to *not* do clever tricks and just take floating-point endpoints at face value.

**Comment by lbenet** [comment]
For reference, see the discussion in #345.

Regarding using `IntervalSets.jl` for set operations, would that satisfy the standard?

**Comment by Kolaru** [comment]
For most of it, it should, but some operation would need to be redefined. For example, for us, union of disjoint interval should return the hull instead of erroring.

While I like the idea of building intervals on a more fundamental package, I feel like in the current state we would loose too much flexibility for a rather small gain. More precisely, given the amount of manipulation we perform of the interval constructor and the restriction we impose on the bounds, I think that type piracy is not an option. And without type piracy, we can not share `..` and would need to wrap `IntervalSets` intervals in ours to use the method defined for them.

**Comment by Kolaru** [comment]
Discussed in today's call, in favor of status quo.
