### ISSUE TITLE
`hypot` broken in Julia 1.4

### ISSUE THREAD

**Issue by mfherbst** [JuliaIntervals/IntervalArithmetic.jl#368]
I've experimented a bit with IntervalArithmetic on Julia 1.4 and similar to #310 now also `hypot` causes a ` StackOverflowError`. In my code I use a hot fix like
```julia
hypot(a::Interval, b::Interval) = √(a^2 + b^2)
```
which solves the problem, but of course one looses the nice numerical stability properties of `hypot` in Base.

Still, I'm happy to polish that into a patch if the maintainers are interested ... or I'm happy for any pointers how to do this more properly.

**Comment by dpsanders** [comment]
Yes please do go ahead and make a PR for `hypot` and maybe also `cbrt`? Thanks a lot! 
Having something is better than nothing... And since we're using interval arithmetic, any rounding errors etc. will just be included into a bigger interval -- we may get a wider interval, but it will still be correct.

**Comment by krish8484** [comment]
Fixed in #390

**Comment by mfherbst** [comment]
Awesome, thanks @krish8484!
