### ISSUE TITLE
Interval creation with .. returns inconsistent types

### ISSUE THREAD

**Issue by remi-garcia** [JuliaIntervals/IntervalArithmetic.jl#416]
I find it strange that:
```Julia
julia> typeof(Float16(0)..Float32(0.5))
Interval{Float32}

julia> typeof(Int(0)..Float32(0.5))
Interval{Float64}
```
I would think that `typeof(Int(0)..Float32(0.5)) == Interval{Float32}`

**Comment by dpsanders** [comment]
You're right that that seems wrong according to Julia's standard promotion mechanism:
```jl
julia> promote(1, 3.5f0)
(1.0f0, 3.5f0)
```

**Comment by dpsanders** [comment]
That is due to using `..`. If you use `interval` it behaves as expected:
```
julia> interval(Int(0), Float32(0.5)) |> typeof
Interval{Float32}
```

**Comment by dpsanders** [comment]
But yes this should be fixed.

**Comment by remi-garcia** [comment]
I don't find what should be the differences between `Interval(a, b)`, `interval(a, b)` and `a..b`. To solve this issue that information would help me.

**Comment by Kolaru** [comment]
`Interval` is the direct construsctor, `interval` checks the bounds and is slightly safer and slower but otherwise equivalent. `..` in the other hand tries to be clever, and thus its behavior is not very well defined, but as mentionned in #396 we should probably not do it and rather rely on macro for the cleverness.

**Comment by lbenet** [comment]
Just to clarify with an example what @Kolaru wrote above, `interval(2, 1)` throws an error because the lower bound is larger than the upper one, while `Interval(2, 1)` does not throw any error.

Regarding `..`, the next example is a nice illustration:
```julia
julia> using IntervalArithmetic

julia> setformat(:full);

julia>  a = Interval(0.1,0.25)
Interval(0.1, 0.25)

julia> b = 0.1 .. 0.25
Interval(0.09999999999999999, 0.25)

julia> 1//10 ∈ a
false

julia> 1//10 ∈ b
true
```
So the "cleverness" to which @Kolaru referred is related to "correct" (outer) rounding.

**Comment by dpsanders** [comment]
This is explained in the docs: https://juliaintervals.github.io/IntervalArithmetic.jl/stable/construction/

**Comment by remi-garcia** [comment]
I'll put a RTFM on the side of my screen. Sorry.
