### ISSUE TITLE
Fix printing of matrices of intervals

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalArithmetic.jl#434]
```jl
julia> M = [1.2..1.6 1.2..1.6; -1..1 -1..1]
2×2 Array{Interval{Float64},2}:
      [1.19999, 1.60001]       [1.19999, 1.60001]
 [-1, 1]                  [-1, 1]
```

**Comment by dpsanders** [comment]
Should be aligned better.

**Comment by lucaferranti** [comment]
quite interesting that Arrays of interval boxes do not suffer from this 🤔 
```
julia> M
2×2 Matrix{Interval{Float64}}:
      [1.19999, 1.60001]       [1.19999, 1.60001]
 [-1, 1]                  [-1, 1]

julia> IntervalBox.(M, 2)
2×2 Matrix{IntervalBox{2, Float64}}:
 [1.19999, 1.60001] × [1.19999, 1.60001]  [1.19999, 1.60001] × [1.19999, 1.60001]
 [-1, 1] × [-1, 1]                        [-1, 1] × [-1, 1]
```

**Comment by dpsanders** [comment]
That's strange. Maybe there's a problem with how the display functions are defined. I'm not sure how Julia checks the width of the output to align it.

**Comment by lucaferranti** [comment]
Based on this prototype, I think indeed the problem is somewhere in the display functions of the package. Now the funny part is figuring out where exactly 🤣 .
```
julia> struct Tmp
       lo
       hi
       end

julia> Base.show(io::IO, a::Tmp) = print(io, "[$(a.lo), $(a.hi)]")

julia> a = Tmp(1.19999, 1.60001)
[1.19999, 1.60001]

julia> b = Tmp(-1, 1)
[-1, 1]

julia> [a a; b b]
2×2 Matrix{Tmp}:
 [1.19999, 1.60001]  [1.19999, 1.60001]
 [-1, 1]             [-1, 1]
```

I don't understand why it works with interval boxes though, based on the source code, I think `join(X.v, " × ")` calls the `representation(X::Interval)` somewhere under the hood, so I don't see what fixes the problem.

``
function representation(X::IntervalBox, format=nothing)

    if format == nothing
        format = display_params.format  # default
    end

    if display_params.format == :full
        return string("IntervalBox(", join(X.v, ", "), ")")

    else
        return join(X.v, " × ")
    end

end
```
