### ISSUE TITLE
`<` and `>` breaks interval?

### ISSUE THREAD

**Issue by Moelf** [JuliaIntervals/IntervalArithmetic.jl#566]
```julia
julia> f(x) = x>0.5
f (generic function with 1 method)

julia> f(0..1)
false

julia> f(1..2)
true
```

is this somehow expected according to IEEE?

**Comment by OlivierHnt** [comment]
I believe so; the reference for this is Table 10.3 of the IEEE Standard 1788-2015.

As a side note: inequalities look broken on 1.0-dev

```Julia
julia> 0..1 > 0.5
true

julia> 0.5 < 0..1
false
```

**Comment by Kolaru** [comment]
Currently `<` implements the `strictLess` function from the standard, as @OlivierHnt pointed out.

However, the symbol is only a suggestion, so we have the freedom to do whatever we want with it. For interoperability with the julia ecosystem, I think the construct should just error. Otherwise, some julia code silently fails (see #165). It is one of the reason that lead to the creation of [NumberIntervals.jl](https://github.com/gwater/NumberIntervals.jl) too.

It is one of the things that would be great to have sorted out for 1.0.

So yes, intervals break `<` and `>`.
