### ISSUE TITLE
Lack of `convert(::Interval{T}, a::Real)`

### ISSUE THREAD

**Issue by lairez** [JuliaIntervals/IntervalArithmetic.jl#580]
I know I am late to the debate (see #558), but I faced the problem of missing conversions in my project. I am implementing [arithmetic circuits](https://en.wikipedia.org/wiki/Arithmetic_circuit_complexity), so there is a type `T` for constants,  typically `Interval{Float64}`, but anything with `+` and `*` defined is fine. To be easily usable, we need to convert the user-provided constants (typically `Int`) to `T`. Why would this work for literally any number type on earth and fail for `Interval{Float64}`?

I understand that promotion is tricky, but conversion is not! The `interval` method, in the form `interval(T, a)`, is a conversion function. So the conversion function exists! It seems very wrong for a Julia library to refuse to fit the general conversion system. Is think that `convert(::Type{Interval{T}}, a::Real) = interval(T, a)` or `Interval{T}(a::Real) = interval(T, a)` are not wrong in any way.

The pro of the PR #558 is “enforce the splitting between `Interval` and `Number` by preventing all conversion except between `Intervals`”. In the future, will you also refuse to compile `2*interval(0.0,1.0)` because `2` is not an interval? After all, this is a kind of implicit conversion. #558 mentions a debate on the matter in #555, but I don't see it.

## Concrete example

I understand that you are not fond of promoting the elements of `[1, 2, 3, 4, interval(5., 6.)]` to anything. So I am fine with the current behavior
```
julia> [1, 2, 3, 4, interval(5., 6.)]
5-element Vector{Real}:
   1
   2
   3
   4
 [5.0, 6.0]
```

But what about `Interval{Float64}[1, 2, 3, 4, interval(5., 6.)]`?
```
julia> Interval{Float64}[1, 2, 3, 4, interval(5., 6.)]
ERROR: MethodError: no method matching Interval{Float64}(::Int64)
```
The user is explicitly telling you he wants a conversion. Why would you force him into non-generic code? Why refusing the `convert` mechanism? It is simple and non surprising (as opposed to the promotion system).

## Current solutions (for me)

* Avoid conversions. Concretely, I write `interval(-40)*x^4-interval(10)*x^2*y-interval(7)*y^3-interval(17)*x^2-interval(75)*x*y+interval(71)*x-interval(44)` instead of `-40*x^4-10*x^2*y-7*y^3-17*x^2-75*x*y+71*x-44`. This is unsustainable. For example, I cannot copy-paste a polynomial that I computed in some computer algebra system.
* Type piracy. I just define `convert(::Type{Interval{T}}, a::Real) = interval(T, a)` and life is good for me, but we know that type piracy is not good in the long term with problems of software composability.
* In the generic code, I replace `convert(T, a)` with `one(T)*a`. It works, but it is so ugly...
* Write specific codes for interval types. No very Juliaesque.

**Comment by OlivierHnt** [comment]
Thank you for the feedback! 🙂

Automatic conversion/promotion is dangerous since it leads to intractable silent errors. Typically, conversion issues arise when someone is relying on a code (often thought out for floating-points arithmetic) and use `Interval` as a drop-in replacement.
So we figured that asking people to explicitly type `interval(T, x)` is better at preventing mistakes than relying on the implicit Julia conversion/promotion system.

Also, you are right that we perform an implicit conversion by allowing mixing `Number` and `Interval` for `+,-,*,/`. This is where it was decided to draw the line; I believe everyone is on board on keeping it that way, but see also #568.

So, `Interval{Float64}[1, 2, 3, 4, interval(5., 6.)]` does not work for the reason mentioned above, that is one is forced to do `interval.(Float64, [1, 2, 3, 4, interval(5., 6.)])`.

> Avoid conversions. Concretely, I write interval(-40)*x^4-interval(10)*x^2*y-interval(7)*y^3-interval(17)*x^2-interval(75)*x*y+interval(71)*x-interval(44) instead of -40*x^4-10*x^2*y-7*y^3-17*x^2-75*x*y+71*x-44. This is unsustainable. For example, I cannot copy-paste a polynomial that I computed in some computer algebra system.

May I ask why you need to convert the `Int` to `interval`? Since `*,-,+,/` are still defined.

> Write specific codes for interval types. No very Juliaesque.

Yes but note that interval arithmetic has specificities that often plays poorly with generic code, @Kolaru gave a nice example recently:
```Julia
function f(x, y)
    if x == y
        return 1
    else
        return exp(x - y)
    end
end
```

**Comment by OlivierHnt** [comment]
When we discuss these aspects, I found that we tend to circle back to "why not just use decorated intervals". Whenever `Number` and `Interval` are being mixed (e.g. with `*` or `convert`), this would just be recorded in an appropriate decoration so that the computation still runs but its output is flagged. The user is then warned that their result may not be rigorous.
This solves #568 with a slightly different approach.
